version: "3.9"

services:
    redis:
        image: redis:7-alpine
        restart: always
        ports:
            - ${REDIS_PORT}:6379
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_PORT=${REDIS_PORT}
        command: redis-server --save 20 1 --loglevel warning ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD}
        volumes:
            - ${REDIS_DATA_PATH}:/data